"""Local public quickstart helpers for SOS."""

from __future__ import annotations

import json
import os
import secrets
import shlex
import socket
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import httpx

from sos.bus.token_store import hash_token, write_tokens_atomic


DEFAULT_PROJECT = "sos-local"
DEFAULT_ALPHA = "alpha"
DEFAULT_BRAVO = "bravo"
DEFAULT_REDIS_PORT = "16379"
DEFAULT_BUS_PORT = "16380"
DEFAULT_MCP_PORT = "16070"
DEFAULT_SQUAD_PORT = "18060"


def _root() -> Path:
    return Path.cwd()


def _local_dir(root: Path) -> Path:
    return root / ".sos" / "local"


def _env_path(root: Path) -> Path:
    return _local_dir(root) / "dev.env"


def _tokens_path(root: Path) -> Path:
    return _local_dir(root) / "tokens.json"


def _data_dir(root: Path) -> Path:
    return root / ".sos" / "data"


def _load_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        parsed = shlex.split(line, posix=True)
        key, value = (parsed[0] if parsed else line).split("=", 1)
        values[key] = value
    return values


def _write_env(path: Path, values: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = ["# Generated by `sos local init`. Safe for local development only."]
    for key in sorted(values):
        body.append(f"{key}={shlex.quote(values[key])}")
    path.write_text("\n".join(body) + "\n", encoding="utf-8")


def _choose_port(preferred: int, *, used: set[int]) -> str:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            if preferred not in used:
                sock.bind(("127.0.0.1", preferred))
                used.add(preferred)
                return str(preferred)
        except OSError:
            pass

    for _ in range(100):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
            sock.bind(("127.0.0.1", 0))
            port = int(sock.getsockname()[1])
            if port not in used:
                used.add(port)
                return str(port)
    raise RuntimeError("could not allocate a free local port")


def _token_record(*, token: str, agent: str, project: str, label: str) -> dict[str, Any]:
    return {
        "token": token,
        "token_hash": hash_token(token),
        "project": project,
        "label": label,
        "active": True,
        "agent": agent,
        "role": "member",
        "scope": "project",
        "permissions": ["send", "inbox", "peers", "broadcast"],
    }


def init_profile(*, root: Path | None = None, force: bool = False) -> dict[str, str]:
    root = root or _root()
    local = _local_dir(root)
    local.mkdir(parents=True, exist_ok=True)
    _data_dir(root).mkdir(parents=True, exist_ok=True)
    env_file = _env_path(root)
    existing = _load_env(env_file)

    if existing and not force:
        data_dir = existing.get("SOS_DATA_DIR")
        if data_dir:
            Path(data_dir).mkdir(parents=True, exist_ok=True)
        return existing

    alpha_token = f"sk-sos-dev-alpha-{secrets.token_hex(12)}"
    bravo_token = f"sk-sos-dev-bravo-{secrets.token_hex(12)}"
    system_token = f"sk-sos-dev-system-{secrets.token_hex(16)}"
    used_ports: set[int] = set()
    redis_port = _choose_port(int(DEFAULT_REDIS_PORT), used=used_ports)
    bus_port = _choose_port(int(DEFAULT_BUS_PORT), used=used_ports)
    mcp_port = _choose_port(int(DEFAULT_MCP_PORT), used=used_ports)
    squad_port = _choose_port(int(DEFAULT_SQUAD_PORT), used=used_ports)
    redis_url = f"redis://localhost:{redis_port}/0"
    bus_url = f"http://localhost:{bus_port}"
    mcp_url = f"http://localhost:{mcp_port}"
    squad_url = f"http://localhost:{squad_port}"
    values = {
        "SOS_HOME": str(root / ".sos"),
        "SOS_DATA_DIR": str(_data_dir(root)),
        "SOS_BUS_TOKENS_PATH": str(_tokens_path(root)),
        "SOS_SYSTEM_TOKEN": system_token,
        "REDIS_PASSWORD": "",
        "REDIS_URL": redis_url,
        "REDIS_HOST": "localhost",
        "REDIS_PORT": redis_port,
        "SOS_LOCAL_PROJECT": DEFAULT_PROJECT,
        "SOS_LOCAL_ALPHA": DEFAULT_ALPHA,
        "SOS_LOCAL_BRAVO": DEFAULT_BRAVO,
        "SOS_LOCAL_ALPHA_TOKEN": alpha_token,
        "SOS_LOCAL_BRAVO_TOKEN": bravo_token,
        "BUS_BRIDGE_PORT": bus_port,
        "MCP_SSE_PORT": mcp_port,
        "SOS_MCP_PORT": mcp_port,
        "SQUAD_URL": squad_url,
        "SOS_BUS_URL": bus_url,
        "SOS_MCP_HEALTH_URL": mcp_url,
        "SOS_SQUAD_PORT": squad_port,
        "SOS_SQUAD_URL": squad_url,
        "SOS_MIRROR_ENABLED": "0",
    }
    _write_env(env_file, values)
    write_tokens_atomic(
        _tokens_path(root),
        [
            _token_record(
                token=alpha_token,
                agent=DEFAULT_ALPHA,
                project=DEFAULT_PROJECT,
                label="Local dev alpha agent",
            ),
            _token_record(
                token=bravo_token,
                agent=DEFAULT_BRAVO,
                project=DEFAULT_PROJECT,
                label="Local dev bravo agent",
            ),
        ],
    )
    return values


def _get_json(url: str, *, token: str | None = None) -> tuple[bool, str]:
    headers = {"Authorization": f"Bearer {token}"} if token else {}
    try:
        response = httpx.get(url, headers=headers, timeout=3.0)
        return response.status_code < 500, f"{response.status_code} {response.text[:120]}"
    except Exception as exc:
        return False, str(exc)


def _post_json(url: str, payload: dict[str, Any], *, token: str) -> dict[str, Any]:
    response = httpx.post(
        url,
        json=payload,
        headers={"Authorization": f"Bearer {token}"},
        timeout=5.0,
    )
    response.raise_for_status()
    return response.json()


def smoke_profile(*, root: Path | None = None) -> int:
    root = root or _root()
    env = init_profile(root=root)
    project = env["SOS_LOCAL_PROJECT"]
    alpha = env["SOS_LOCAL_ALPHA"]
    bravo = env["SOS_LOCAL_BRAVO"]
    alpha_token = env["SOS_LOCAL_ALPHA_TOKEN"]
    bravo_token = env["SOS_LOCAL_BRAVO_TOKEN"]
    system_token = env["SOS_SYSTEM_TOKEN"]
    bus_url = os.environ.get("SOS_BUS_URL", env.get("SOS_BUS_URL", "http://localhost:16380"))
    mcp_url = os.environ.get("SOS_MCP_HEALTH_URL", env.get("SOS_MCP_HEALTH_URL", "http://localhost:16070"))
    squad_url = os.environ.get("SOS_SQUAD_URL", env.get("SOS_SQUAD_URL", "http://localhost:18060"))

    checks: list[tuple[str, bool, str]] = []

    try:
        import redis

        redis.Redis.from_url(env.get("REDIS_URL", "redis://localhost:16379/0"), decode_responses=True).ping()
        checks.append(("Redis", True, "PONG"))
    except Exception as exc:
        checks.append(("Redis", False, str(exc)))

    for name, url in (
        ("Bus bridge", f"{bus_url}/health"),
        ("MCP", f"{mcp_url}/health"),
        ("Squad", f"{squad_url}/health"),
    ):
        ok, detail = _get_json(url)
        checks.append((name, ok, detail))

    if all(ok for _, ok, _ in checks):
        try:
            msg = f"S079 smoke {int(time.time())}"
            sent = _post_json(
                f"{bus_url}/send",
                {"from": alpha, "to": bravo, "text": msg, "project": project},
                token=alpha_token,
            )
            inbox = httpx.get(
                f"{bus_url}/inbox",
                params={"agent": bravo, "project": project, "limit": 10},
                headers={"Authorization": f"Bearer {bravo_token}"},
                timeout=5.0,
            )
            inbox.raise_for_status()
            found = msg in inbox.text
            checks.append(("Bus send/inbox", found, sent.get("message_id", "queued")))
        except Exception as exc:
            checks.append(("Bus send/inbox", False, str(exc)))

    if all(ok for _, ok, _ in checks):
        try:
            task_id = f"s079-smoke-{int(time.time())}"
            task = _post_json(
                f"{squad_url}/tasks",
                {
                    "id": task_id,
                    "squad_id": "public-smoke",
                    "title": "S079 public smoke task",
                    "description": "Created by sos local doctor.",
                    "labels": ["smoke"],
                },
                token=system_token,
            )
            claim = _post_json(
                f"{squad_url}/tasks/{task_id}/claim",
                {"assignee": alpha, "attempt": 0},
                token=system_token,
            )
            completed = _post_json(
                f"{squad_url}/tasks/{task_id}/complete",
                {
                    "result": {"summary": "S079 local smoke complete"},
                    "claim_token": claim.get("claim_token"),
                },
                token=system_token,
            )
            status = completed.get("status") or completed.get("task", {}).get("status")
            checks.append(("Task create/claim/complete", status in {"completed", "done"}, task_id))
        except Exception as exc:
            checks.append(("Task create/claim/complete", False, str(exc)))

    mirror_url = os.environ.get("MIRROR_URL") or os.environ.get("SOS_MIRROR_URL")
    if mirror_url:
        ok, detail = _get_json(f"{mirror_url.rstrip('/')}/health")
        checks.append(("Mirror optional", ok, detail))
    else:
        checks.append(("Mirror optional", True, "disabled"))

    failed = False
    for name, ok, detail in checks:
        mark = "OK" if ok else "FAIL"
        print(f"[{mark}] {name}: {detail}")
        failed = failed or not ok
    return 1 if failed else 0


def run_migrations() -> int:
    env = init_profile()
    proc_env = os.environ.copy()
    proc_env.update(env)
    cmd = [
        sys.executable,
        "-m",
        "alembic",
        "-c",
        "sos/services/squad/alembic.ini",
        "upgrade",
        "head",
    ]
    return subprocess.call(cmd, env=proc_env)
