#!/usr/bin/env bash
# Generate TypeScript types from exported JSON Schemas.
#
# Reads every *.json in sos/contracts/ports/schemas/ and writes a
# matching .ts file to /home/mumega/inkwell/kernel/ports/generated/.
# A single barrel (index.ts) re-exports every generated module so the
# Inkwell kernel can `import * from "./generated"`.
#
# Idempotent — runs as many times as you like without side effects.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
SCHEMAS_DIR="${REPO_ROOT}/sos/contracts/ports/schemas"
# Portable across machines + CI checkouts — override with
# INKWELL_ROOT=/path/to/inkwell when running outside Hadi's workstation.
INKWELL_ROOT="${INKWELL_ROOT:-/home/mumega/inkwell}"
OUT_DIR="${INKWELL_ROOT}/kernel/ports/generated"
JSON2TS="${INKWELL_ROOT}/node_modules/.bin/json2ts"

if [[ ! -d "${INKWELL_ROOT}" ]]; then
  echo "gen_ts_types: INKWELL_ROOT does not exist: ${INKWELL_ROOT}" >&2
  echo "  set INKWELL_ROOT to the Inkwell checkout path." >&2
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "gen_ts_types: npm not found on PATH. Install Node.js first." >&2
  exit 1
fi

if [[ ! -d "${SCHEMAS_DIR}" ]]; then
  echo "gen_ts_types: schemas dir does not exist yet: ${SCHEMAS_DIR}" >&2
  echo "  run: python ${SCRIPT_DIR}/export_port_schemas.py" >&2
  exit 1
fi

# Install json-schema-to-typescript in the Inkwell workspace if missing.
if [[ ! -x "${JSON2TS}" ]]; then
  echo "gen_ts_types: installing json-schema-to-typescript in Inkwell..." >&2
  npm install --prefix "${INKWELL_ROOT}" --save-dev json-schema-to-typescript >/dev/null
fi

mkdir -p "${OUT_DIR}"

# Sweep stale .ts files so renames/removals don't leave ghosts behind
# (they'd still be re-exported by the barrel below).
find "${OUT_DIR}" -maxdepth 1 -name '*.ts' -not -name 'index.ts' -delete

shopt -s nullglob
schema_files=( "${SCHEMAS_DIR}"/*.json )
shopt -u nullglob

if (( ${#schema_files[@]} == 0 )); then
  echo "gen_ts_types: no schemas in ${SCHEMAS_DIR} — nothing to do." >&2
  # Still (re)write an empty barrel so consumers get a valid module.
  : > "${OUT_DIR}/index.ts"
  exit 0
fi

declare -a modules=()
for schema_file in "${schema_files[@]}"; do
  base="$(basename "${schema_file}" .json)"
  out_file="${OUT_DIR}/${base}.ts"
  echo "gen_ts_types: ${base}.json -> ${base}.ts"
  "${JSON2TS}" -i "${schema_file}" -o "${out_file}" >/dev/null
  modules+=( "${base}" )
done

# Write a deterministic barrel: sorted module names, one export per line.
IFS=$'\n' sorted=( $(printf '%s\n' "${modules[@]}" | sort) )
unset IFS

barrel="${OUT_DIR}/index.ts"
{
  echo "// AUTO-GENERATED by scripts/gen_ts_types.sh — do not edit by hand."
  echo "// Run \`make contracts\` from the SOS repo to regenerate."
  echo ""
  for module in "${sorted[@]}"; do
    printf 'export * from "./%s";\n' "${module}"
  done
} > "${barrel}"

echo "gen_ts_types: wrote ${#sorted[@]} module(s) and barrel ${barrel}"
