#!/bin/bash
# SOS Tenant Setup — One script to onboard a new agent/customer to the server.
#
# Usage:
#   sudo bash sos/cli/tenant-setup.sh <name> [--model claude] [--repos user/repo,user/repo2]
#
# What it does:
#   1. Creates Linux user (isolated)
#   2. Scaffolds home directory (symlinks SOS + Mirror)
#   3. Generates bus + mirror tokens
#   4. Copies .claude/ config from git repo (if provided)
#   5. Sets up shared tmux socket (no sudo needed for wake daemon)
#   6. Configures hooks for bus inbox
#   7. Wires dynamic routing for wake daemon
#   8. Registers agent on bus
#   9. Launches Claude Code in tmux
#   10. Tests delivery
#
# After running: agent is alive on server, receiving bus messages, building.

set -euo pipefail

# --- Parse args ---
NAME="${1:?Usage: tenant-setup.sh <name> [--model MODEL] [--repos REPOS] [--config-repo REPO]}"
shift

MODEL="claude"
REPOS=""
CONFIG_REPO=""
SKILLS=""
ROLE="builder"
DESCRIPTION=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --model) MODEL="$2"; shift 2 ;;
        --repos) REPOS="$2"; shift 2 ;;
        --config-repo) CONFIG_REPO="$2"; shift 2 ;;
        --skills) SKILLS="$2"; shift 2 ;;
        --role) ROLE="$2"; shift 2 ;;
        --description) DESCRIPTION="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

SOS_HOME="$(getent passwd mumega | cut -d: -f6)"
SOS_DIR="$SOS_HOME/SOS"
MIRROR_DIR="$SOS_HOME/mirror"
SHARED_TMUX_DIR="/tmp/sos-tmux"
HOME_DIR="/home/$NAME"

echo "============================================"
echo " SOS Tenant Setup: $NAME"
echo "============================================"

# --- Step 1: Create Linux user ---
if id "$NAME" &>/dev/null; then
    echo "[1/10] User $NAME already exists"
else
    useradd -m -s /bin/bash "$NAME"
    echo "[1/10] Created user: $NAME"
fi

# --- Step 2: Scaffold home directory ---
sudo -u "$NAME" mkdir -p "$HOME_DIR/.sos" "$HOME_DIR/.claude/hooks" "$HOME_DIR/.claude/agents" "$HOME_DIR/.claude/memory" "$HOME_DIR/projects" "$HOME_DIR/scripts"

# Symlink SOS + Mirror (inherits core)
ln -sf "$SOS_DIR" "$HOME_DIR/SOS" 2>/dev/null || true
ln -sf "$MIRROR_DIR" "$HOME_DIR/mirror" 2>/dev/null || true

# Add to mumega group for SOS read access
usermod -aG mumega "$NAME" 2>/dev/null || true

echo "[2/10] Home directory scaffolded"

# --- Step 3: Generate tokens ---
BUS_TOKEN="sk-bus-${NAME}-$(openssl rand -hex 8)"
MIRROR_TOKEN="sk-mumega-${NAME}-$(openssl rand -hex 8)"
MCP_URL="https://mcp.mumega.com/sse/${BUS_TOKEN}"

# Store bus token (atomic)
TOKENS_FILE="$SOS_DIR/sos/bus/tokens.json"
if [ -f "$TOKENS_FILE" ]; then
    # Check if already exists
    if grep -q "\"project\": \"$NAME\"" "$TOKENS_FILE"; then
        echo "[3/10] Bus token already exists for $NAME"
        BUS_TOKEN=$(python3 -c "import json; tokens=json.load(open('$TOKENS_FILE')); print([t['token'] for t in tokens if t.get('project')=='$NAME'][0])" 2>/dev/null || echo "$BUS_TOKEN")
    else
        python3 -c "
import json, sys
from datetime import datetime, timezone
tokens = json.load(open('$TOKENS_FILE'))
tokens.append({
    'token': '$BUS_TOKEN',
    'token_hash': '',
    'project': '$NAME',
    'label': '$NAME agent',
    'active': True,
    'created_at': datetime.now(timezone.utc).isoformat()
})
with open('$TOKENS_FILE', 'w') as f:
    json.dump(tokens, f, indent=2)
"
        echo "[3/10] Bus token generated: ${BUS_TOKEN:0:20}..."
    fi
fi

# Store mirror token
MIRROR_KEYS="$SOS_HOME/.sos/mirror_keys.json"
mkdir -p "$(dirname "$MIRROR_KEYS")"
if [ -f "$MIRROR_KEYS" ] && grep -q "\"agent_slug\": \"$NAME\"" "$MIRROR_KEYS"; then
    echo "       Mirror token already exists"
else
    python3 -c "
import json, os
from datetime import datetime, timezone
path = '$MIRROR_KEYS'
keys = json.load(open(path)) if os.path.exists(path) else []
keys.append({
    'key': '$MIRROR_TOKEN',
    'agent_slug': '$NAME',
    'created_at': datetime.now(timezone.utc).isoformat(),
    'active': True,
    'label': '$NAME mirror access'
})
with open(path, 'w') as f:
    json.dump(keys, f, indent=2)
" 2>/dev/null || true
    echo "       Mirror token generated"
fi

# --- Step 4: Write tenant config ---
# Allocate Redis DB number for tenant isolation
REDIS_DB=$(python3 -c "import sys; sys.path.insert(0, '$SOS_DIR'); from sos.services.bus.tenants import register_tenant; print(register_tenant('$NAME'))")
echo "       Redis DB allocated: $REDIS_DB"

cat > "/tmp/sos-env-$NAME" << ENVEOF
# $NAME SOS Configuration — generated by tenant-setup.sh
AGENT=$NAME
SOS_TOKEN=$BUS_TOKEN
MIRROR_TOKEN=$MIRROR_TOKEN
MCP_URL=$MCP_URL
REDIS_URL=redis://localhost:6379/${REDIS_DB}
MIRROR_URL=http://localhost:8844
ENVEOF
cp "/tmp/sos-env-$NAME" "$HOME_DIR/.sos/.env"
chown "$NAME:$NAME" "$HOME_DIR/.sos/.env"
chmod 600 "$HOME_DIR/.sos/.env"

# MCP settings
cat > "/tmp/sos-mcp-$NAME" << MCPEOF
{
  "mcpServers": {
    "sos": {
      "type": "sse",
      "url": "$MCP_URL"
    }
  },
  "hooks": {
    "UserPromptSubmit": [
      {
        "matcher": "",
        "hooks": [
          {
            "type": "command",
            "command": "$HOME_DIR/.claude/hooks/check-inbox.sh",
            "timeout": 8000
          }
        ]
      }
    ]
  },
  "skipDangerousModePermissionPrompt": true
}
MCPEOF
cp "/tmp/sos-mcp-$NAME" "$HOME_DIR/.claude/settings.json"
chown "$NAME:$NAME" "$HOME_DIR/.claude/settings.json"

echo "[4/10] Config written (.sos/.env + .claude/settings.json)"

# --- Step 5: Clone repos ---
if [ -n "$REPOS" ]; then
    IFS=',' read -ra REPO_LIST <<< "$REPOS"
    for repo in "${REPO_LIST[@]}"; do
        repo_name="${repo##*/}"
        dest="$HOME_DIR/projects/$repo_name"
        if [ ! -d "$dest" ]; then
            sudo -u "$NAME" git clone "https://github.com/$repo.git" "$dest" 2>/dev/null || \
            git clone "https://github.com/$repo.git" "$dest" 2>/dev/null && \
            chown -R "$NAME:$NAME" "$dest" || true
            echo "       Cloned: $repo"
        else
            echo "       Already exists: $repo_name"
        fi
    done
    echo "[5/10] Repos cloned"
else
    echo "[5/10] No repos specified, skipping"
fi

# --- Step 6: Copy .claude/ config from git repo ---
if [ -n "$CONFIG_REPO" ]; then
    TEMP="/tmp/sos-config-$NAME"
    rm -rf "$TEMP"
    git clone "https://github.com/$CONFIG_REPO.git" "$TEMP" 2>/dev/null || true
    if [ -d "$TEMP" ]; then
        # Copy everything from config repo to .claude/
        cp -r "$TEMP"/* "$HOME_DIR/.claude/" 2>/dev/null || true
        cp "$TEMP"/.mcp.json "$HOME_DIR/.mcp.json" 2>/dev/null || true
        chown -R "$NAME:$NAME" "$HOME_DIR/.claude/" "$HOME_DIR/.mcp.json" 2>/dev/null || true
        rm -rf "$TEMP"
        echo "[6/10] Config imported from $CONFIG_REPO"
    else
        echo "[6/10] Config repo not found, using defaults"
    fi
else
    echo "[6/10] No config repo, using defaults"
fi

# --- Step 7: Create inbox check hook ---
cat > "$HOME_DIR/.claude/hooks/check-inbox.sh" << 'HOOKEOF'
#!/bin/bash
# Bus inbox check — runs on every user prompt
set -euo pipefail
AGENT=$(grep "^AGENT=" ~/.sos/.env 2>/dev/null | cut -d= -f2 || echo "unknown")
TOKEN=$(grep "^SOS_TOKEN=" ~/.sos/.env 2>/dev/null | cut -d= -f2 || echo "")
[ -z "$TOKEN" ] && exit 0

inbox=$(curl --connect-timeout 2 --max-time 5 -sf \
  "https://mcp.mumega.com/sse/$TOKEN" \
  -H "Accept: application/json" 2>/dev/null || echo "")

# Also check via direct MCP
QUEUE_FILE="/tmp/${AGENT}-pending-msgs.json"
if [ -f "$QUEUE_FILE" ]; then
  count=$(jq -r "length" "$QUEUE_FILE" 2>/dev/null || echo "0")
  if [ "$count" != "0" ] && [ "$count" != "null" ]; then
    echo "[bus] $count queued message(s):"
    jq -r ".[] | \"  [\(.from // \"unknown\")] \(.text // \"\")\"" "$QUEUE_FILE" 2>/dev/null || true
    echo "[]" > "$QUEUE_FILE"
  fi
fi
exit 0
HOOKEOF
chmod +x "$HOME_DIR/.claude/hooks/check-inbox.sh"
chown "$NAME:$NAME" "$HOME_DIR/.claude/hooks/check-inbox.sh"
echo "[7/10] Inbox hook installed"

# --- Step 8: Set up shared tmux socket ---
mkdir -p "$SHARED_TMUX_DIR"
chmod 1777 "$SHARED_TMUX_DIR"

echo "[8/10] Shared tmux directory ready ($SHARED_TMUX_DIR)"

# --- Step 9: Wire dynamic routing ---
ROUTING_FILE="$SOS_HOME/.sos/agent_routing.json"
python3 -c "
import json, os
path = '$ROUTING_FILE'
routing = json.load(open(path)) if os.path.exists(path) else {}
routing['$NAME'] = 'tmux'
routing.pop('_comment', None)
routing['_comment'] = 'Dynamic routing overrides. Wake daemon checks this file.'
with open(path, 'w') as f:
    json.dump(routing, f, indent=2)
" 2>/dev/null || true
echo "[9/10] Wake daemon routing configured"

# --- Step 10: Generate CLAUDE.md ---
SKILLS_STR="${SKILLS:-general}"
cat > "$HOME_DIR/CLAUDE.md" << CLAUDEEOF
# $NAME

## Identity
You are $NAME, a $ROLE agent. Model: $MODEL.
$DESCRIPTION

## System
- **SOS** → ~/SOS/ (symlinked, auto-updates)
- **Mirror** → ~/mirror/ (tenant-isolated by token)
- **Bus** → mcp__sos__send/inbox/peers/broadcast
- **Memory** → mcp__sos__remember/recall

## Skills
$SKILLS_STR

## Bus Identity
- Agent: $NAME
- Tokens: ~/.sos/.env
- MCP: ~/.claude/settings.json

## Communication
Use mcp__sos__send for all team communication.

## Red Lines
- No private data exfiltration
- No external actions without approval
- Quality > speed
CLAUDEEOF
chown "$NAME:$NAME" "$HOME_DIR/CLAUDE.md"

echo "[10/10] CLAUDE.md generated"

# --- Launch ---
echo ""
echo "============================================"
echo " SETUP COMPLETE: $NAME"
echo "============================================"
echo ""
echo " Home:        $HOME_DIR"
echo " Bus Token:   $BUS_TOKEN"
echo " Mirror:      $MIRROR_TOKEN"
echo " MCP URL:     $MCP_URL"
echo ""
echo " To launch Claude Code:"
echo "   sudo -u $NAME tmux new-session -d -s $NAME -S $SHARED_TMUX_DIR/$NAME -c $HOME_DIR"
echo "   sudo -u $NAME tmux send-keys -t $NAME -S $SHARED_TMUX_DIR/$NAME 'claude --dangerously-skip-permissions' Enter"
echo ""
echo " To attach:"
echo "   tmux -S $SHARED_TMUX_DIR/$NAME attach -t $NAME"
echo ""
echo " MCP Config (give to agent):"
echo "   {\"mcpServers\":{\"mumega\":{\"url\":\"$MCP_URL\"}}}"
echo ""
echo "============================================"
